FROM nginx
COPY . /usr/share/nginx/html
COPY ./NGINX/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 8000

RUN apt-get update \
&& apt-get install curl

# FROM httpd:2.4
# COPY test.html /usr/local/apache2/htdocs/