# FROM nginx
# COPY . /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

FROM httpd:2.4
COPY ./HTTPD/. /usr/local/apache2/htdocs/
EXPOSE 80

RUN apt-get update \
&& apt-get install curl